import { EnhancedEventEmitter } from 'mediasoup-client/lib/EnhancedEventEmitter';
import { HandlerFactory } from 'mediasoup-client/lib/handlers/HandlerInterface';
import * as media from './media';
import { AppMediaStream } from './AppMediaStream';
export declare type WorkerSettings = {
    /**
     * Logging level for logs generated by the worker.
     */
    logLevel?: WorkerLogLevel;
};
export declare type WorkerLogLevel = 'debug' | 'warn' | 'error' | 'none';
export declare class Worker extends EnhancedEventEmitter {
    private _child?;
    private readonly _pid;
    private readonly _channel;
    private _closed;
    private readonly _streams;
    private readonly _handlers;
    /**
     * @emits died - (error: Error)
     * @emits @success
     * @emits @failure - (error: Error)
     */
    constructor({ logLevel }: WorkerSettings);
    /**
     * Worker process identifier (PID).
     */
    readonly pid: number;
    /**
     * Whether the Worker is closed.
     */
    readonly closed: boolean;
    /**
     * Close the Worker.
     */
    close(): void;
    /**
     * Create a AppMediaStream with audio/video tracks.
     */
    getAppMedia(constraints: media.AppMediaStreamConstraints): Promise<AppMediaStream>;
    /**
     * Create a mediasoup-client HandlerFactory.
     */
    createHandlerFactory(): HandlerFactory;
}
//# sourceMappingURL=Worker.d.ts.map