import { EnhancedEventEmitter } from 'mediasoup-client/lib/EnhancedEventEmitter';
import { HandlerFactory } from 'mediasoup-client/lib/handlers/HandlerInterface';
import * as media from './media';
import { AiortcMediaStream } from './AiortcMediaStream';
export declare type WorkerSettings = {
    /**
     * Logging level for logs generated by the Python subprocess.
     */
    logLevel?: WorkerLogLevel;
};
export declare type WorkerLogLevel = 'debug' | 'warn' | 'error' | 'none';
export declare class Worker extends EnhancedEventEmitter {
    private _child?;
    private readonly _pid;
    private readonly _channel;
    private _closed;
    private readonly _handlers;
    /**
     * @emits died - (error: Error)
     * @emits @success
     * @emits @failure - (error: Error)
     */
    constructor({ logLevel }: WorkerSettings);
    /**
     * Worker process identifier (PID).
     */
    get pid(): number;
    /**
     * Whether the Worker is closed.
     */
    get closed(): boolean;
    /**
     * Close the Worker.
     */
    close(): void;
    dump(): Promise<any>;
    /**
     * Create a AiortcMediaStream with audio/video tracks.
     */
    getUserMedia(constraints: media.AiortcMediaStreamConstraints): Promise<AiortcMediaStream>;
    /**
     * Create a mediasoup-client HandlerFactory.
     */
    createHandlerFactory(): HandlerFactory;
}
//# sourceMappingURL=Worker.d.ts.map