import { EnhancedEventEmitter } from 'mediasoup-client/lib/EnhancedEventEmitter';
import { MediaKind } from 'mediasoup-client/lib/RtpParameters';
import { FakeRTCDataChannel } from './FakeRTCDataChannel';
import { FakeRTCStatsReport } from './FakeRTCStatsReport';
import { HandlerSendDataChannelOptions } from 'mediasoup-client/lib/handlers/HandlerInterface';
export declare type WorkerLogLevel = 'debug' | 'warn' | 'error' | 'none';
export declare type WorkerSettings = {
    /**
     * RTCConfiguration object.
     */
    rtcConfiguration?: RTCConfiguration;
    /**
     * Logging level for logs generated by the media worker subprocesses. Valid
     * values are 'debug', 'warn', 'error' and 'none'. Default 'none'.
     */
    logLevel?: WorkerLogLevel;
};
export declare type WorkerState = 'connecting' | 'open' | 'closed';
export declare type WorkerSendOptions = {
    kind: MediaKind;
    sourceType: 'device' | 'file' | 'url';
    sourceValue?: string;
};
declare type WorkerSendResult = {
    trackId: string;
};
export declare class Worker extends EnhancedEventEmitter {
    private _child?;
    private readonly _channel;
    private _state;
    /**
     * @emits open
     * @emits failed - (error: Error)
     * @emits error - (error: Error)
     */
    constructor({ rtcConfiguration, logLevel }?: WorkerSettings);
    /**
     * Close the Worker.
     */
    close(): void;
    getState(): WorkerState;
    getRtpCapabilities(): Promise<string>;
    getLocalDescription(): Promise<RTCSessionDescription>;
    setLocalDescription(desc: RTCSessionDescription): Promise<void>;
    setRemoteDescription(desc: RTCSessionDescription): Promise<void>;
    createOffer({ iceRestart }?: RTCOfferOptions): Promise<RTCSessionDescription>;
    createAnswer(): Promise<RTCSessionDescription>;
    addTrack(options: WorkerSendOptions): Promise<WorkerSendResult>;
    removeTrack(trackId: string): Promise<void>;
    getMid(trackId: string): Promise<string | undefined>;
    enableTrack(trackId: string): void;
    disableTrack(trackId: string): void;
    createDataChannel(options: HandlerSendDataChannelOptions): Promise<FakeRTCDataChannel>;
    getTransportStats(): Promise<FakeRTCStatsReport>;
    getSenderStats(mid: string): Promise<FakeRTCStatsReport>;
    getReceiverStats(mid: string): Promise<FakeRTCStatsReport>;
    private _handleWorkerNotifications;
}
export {};
//# sourceMappingURL=Worker.d.ts.map